language: php
php:
  - 7.1
  - 7.2

install: composer install
script:
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=src/Protos src/
  - ./vendor/bin/phpunit -c tests/app-tests.xml
  - ./vendor/bin/phpstan analyse src --level max
  - ./vendor/bin/psalm --show-info=false