<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/dice.proto

namespace MeadSteve\DiceApi\Protos\V1\Meta;

class Dice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abf010a1170726f746f732f646963652e70726f746f121b4d6561645374" .
            "6576652e446963654170692e50726f746f732e563122230a044469636512" .
            "0d0a0576616c7565180120012805120c0a046e616d65180220012809223b" .
            "0a08526573706f6e7365122f0a046469636518012003280b32212e4d6561" .
            "6453746576652e446963654170692e50726f746f732e56312e4469636542" .
            "23e202204d65616453746576655c446963654170695c50726f746f735c56" .
            "315c4d657461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

