name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: | 
          /var/lib/docker
        key: ${{ runner.os }}-${{ hashFiles('Dockerfile', 'composer.*', 'docker/**') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: experimenting
      run: docker info
    - name: Build test containers
      run: docker-compose -f docker-compose-test.yml build
    - name: Run tests within container
      run: ./run_tests.sh
