name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        key: dockache-${{ runner.os }}-${{ hashFiles('Dockerfile', 'composer.*', 'docker/**') }}
        restore-keys: |
          dockache-${{ runner.os }}-${{ hashFiles('Dockerfile', 'composer.*', 'docker/**') }}
    - name: Run tests using docker-compose
      run: ./run_tests.sh
